//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public class DoanhNghiep
    {
        public int Id { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string DiaChi { get; set; }
        public string NguoiDaiDien { get; set; }
        public string ChucVu { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public bool Active { get; set; }
        public string DoanhNghiepCode { get; set; }
    }

    public class ObjFromJson
    {
        public string SolrID { get; set; }
        public OptionFilter Option { get; set; }
        public List<DoanhNghiepFirstModel> LtsItems { get; set; }
    }

    public class OptionFilter
    {
        public int TotalRow { get; set; }
    }
}
